### ISSUE TITLE
[BUG] Repeated crashes at a location in the overworld

### ISSUE THREAD

**Issue by forcesinbalance** [theomenden/OmenCraft#1] opened 2022-11-05 12:43 UTC
In the initial server world launched with the modpack, I reached location 6, 34, 8 in the overworld, where I stopped to access options. I exited the menu without changing settings, and the Minecraft client froze. Exiting and restarting resulted in being kicked from the server each; the kick occurred after the minimap rendered, but before world textures were visible. The kick error message was in relation to net.minecraft.class_341@3b38f1f2. 

Client logs show a number of warnings and errors, but the crucial one seems to be connected with JustEnoughResources. If the corruption is connected to failed attempts to populate loot tables, it would account for why we're seeing problems in places with generated chests and barrels. 

Representative client log attached.
[CrashOnLoad.log](https://github.com/theomenden/OmenCraft/files/9943816/CrashOnLoad.log)

**Comment by AluTheCrow** [comment] 2022-11-06 00:56
Thank you for submitting this.

1.) One of the sound mods is conflicting, causing a loadin/mixin issue somewhere down the line. 

2.) Resolving issues with REI - replacement sought. Well continue to update as we find issues. 

I'm leaning towards REI issue due to the fact that we currently have other modpacks moving away from it, in favor JEI.

**Comment by AluTheCrow** [comment] 2022-11-07 07:27
Removed JEI, and replaced with REI.

We'll test this out to see if the issue is resolved.

**Comment by AluTheCrow** [comment] 2022-11-07 17:15
Update: Chunk is still corrupted after change to REI. 

Looking into other issues - specifically with sounds.

**Comment by AluTheCrow** [comment] 2022-11-09 19:34
Update:
In testing this has been resolved. Waiting for live deployment.

**Comment by AluTheCrow** [comment] 2022-11-11 04:41
Deployment on a live server hasn't generated corrupted chunks due to the sound issues since the removal of mods specified in 0.11.10+ versions of the pack. Will continue to explore and search for these areas.

**Closed as completed by AluTheCrow** 2022-11-11 04:41 UTC
Labels: bug
