### ISSUE TITLE
Server Crash When Using Seed Recycler on 0.11.2219 Version [BUG]

### ISSUE THREAD

**Issue by LadyKatieSue** [theomenden/OmenCraft#9] opened 2022-12-02 03:59 UTC
**Describe the bug**
I created the seed recycler from the Croparia mod to get rid of massive amounts of seeds that I can't just compost. However, when I right click on the recycler to open it up, my game crashes & it seems the entire server crashes as well, as I cannot connect to the server when taken back to the multiplayer menu until it is done reloading. I tried both versions of 0.11.2219, the hf one & the non-hf one, & results were the same.

**To Reproduce**
1. Build & place a seed recycler
2. Right click on recycler & watch it crash everything

**Expected behavior**
Opening up the recycler to dump excess seeds & an energy source into to make fruits from seeds.

**Environment**
Omen Craft: 0.11.2219
Minecraft version: 1.19.2
Operating System: Windows 10 (amd64) version 10.0

**Additional Info**
Crash report was not generated. I'm providing a log from the /logs folder instead.

**Log**
[2022-12-01-2.log](https://github.com/theomenden/OmenCraft/files/10138006/2022-12-01-2.log)

**Comment by LadyKatieSue** [comment] 2022-12-02 20:27
Additional note: it works fine on single player, it only crashes the multiplayer server.

**Comment by AluTheCrow** [comment] 2022-12-04 00:28
This is still under review, but I've been unable to reproduce this.

**Comment by LadyKatieSue** [comment] 2022-12-04 00:36
Well when I tried it out on single player, I wasn't all the impressed. If you aren't able to fix it, no big deal, I won't miss it. I'm sure there are other, better things to work on lol.

**Comment by AluTheCrow** [comment] 2023-03-06 16:54
Fixed in the latest version (actually was fixed earlier, but I'm silly and forgot to update)

Fix - removed the mod

**Closed as completed by AluTheCrow** 2023-03-06 16:54 UTC
Labels: bug
